### PR TITLE
Support NodeJS 14 & 16

### PR DESCRIPTION
**Pull request by Newbie012**
#### Description of changes

Supports NodeJS 16 runtime version

#### Checklist

- [x] PR description included

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by aaronmcadam** [comment]
It'd be nice to have the latest LTS version too, which is 14.

**Comment by Newbie012** [comment]
> It'd be nice to have the latest LTS version too, which is 14.

Added

**Comment by aaronmcadam** [comment]
> > It'd be nice to have the latest LTS version too, which is 14.
> 
> Added

Nice, thanks so much! 🙏

**Comment by michaelbrewer** [comment]
Nice! I did not know Node 14 was **not** supported, and when Node 12 end of life coming up. It would be great to support Node 14 at least.

**Comment by 0xR** [comment]
What do we need to get this merged? I'd like to be able to use the LTS version of Node (14) to build my apps. Currently I have to have to avoid using optional chaining, nullish coalescing and toplevel await in my build scripts.

I'd prefer not having to maintain my own docker image for this.

**Comment by technoknol** [comment]
When will this be merged and supported officially? Looks like lot of people are waiting including me.

**Comment by aaronmcadam** [comment]
Just a note to say that the LTS version is now 16.13.0: https://nodejs.org/en/blog/release/v16.13.0/

**Comment by mawhtin** [comment]
+1 for LTS 16 please.

A few of the node function signatures have changed for the better and we'd like to use them

**Comment by Xenarc** [comment]
Hi, for those suffering from the limitation of having to use older node versions for your amplify builds, I have a temporary work-around. Rather than building and maintaining your own docker image (from this PR's DockerFile), there already exists a publically hosted image from AWS on the public Elastic Container Registry [here](https://gallery.ecr.aws/sam/build-nodejs14.x) which has worked sufficiently for my needs (and hopefully yours too - I haven't fully tested the image in all use-cases etc). Unfortunatly I havn't been able to find a simmilar Nodejs 16.x image there. 
For a quick fix, in the amplify console, proceed to the Build Settings page > Build Image Settings, then after clicking 'Edit', change the default build image URI to `public.ecr.aws/sam/build-nodejs14.x:latest`.
Hope this saves others some time :)

**Comment by 123joshuawu** [comment]
In the AWS Amplify console provision logs, it looks like these changes are shown in the Dockerfile, but when I try to use `$VERSION_NODE_16` the environment variable is empty?

**Review by Sekaiichi — APPROVED** [review]

**Comment by Newbie012** [comment]
There's already support for these versions. Closing this issue as it's no longer relevant.

Thanks!

**Pull request closed without merging**
